#!/bin/bash
# Demonstration script showing all API endpoints

echo "======================================================"
echo "Retraction Watch API - Feature Demonstration"
echo "======================================================"
echo ""

echo "1. API Root Endpoint"
echo "   GET /"
curl -s http://localhost:8000/ | python -m json.tool
echo ""
echo "------------------------------------------------------"
echo ""

echo "2. Query Retractions (paginated)"
echo "   GET /retractions?page=1&page_size=2"
curl -s "http://localhost:8000/retractions?page=1&page_size=2" | python -c "import sys, json; data=json.load(sys.stdin); print(json.dumps({'total': data['total'], 'page': data['page'], 'returned': len(data['retractions']), 'sample_title': data['retractions'][0]['title'][:60] + '...'}, indent=2))"
echo ""
echo "------------------------------------------------------"
echo ""

echo "3. Filter by Author"
echo "   GET /retractions?author=Boldt"
curl -s "http://localhost:8000/retractions?author=Boldt&page_size=1" | python -c "import sys, json; data=json.load(sys.stdin); print(json.dumps({'total_results': data['total'], 'sample_author': data['retractions'][0]['author'][:50] + '...'}, indent=2))"
echo ""
echo "------------------------------------------------------"
echo ""

echo "4. Filter by Year"
echo "   GET /retractions?year=2025"
curl -s "http://localhost:8000/retractions?year=2025&page_size=1" | python -c "import sys, json; data=json.load(sys.stdin); print(json.dumps({'total_in_2025': data['total'], 'sample_date': data['retractions'][0]['retraction_date']}, indent=2))"
echo ""
echo "------------------------------------------------------"
echo ""

echo "5. Filter by Journal"
echo "   GET /retractions?journal=Nature"
curl -s "http://localhost:8000/retractions?journal=Nature&page_size=1" | python -c "import sys, json; data=json.load(sys.stdin); print(json.dumps({'nature_journals': data['total'], 'sample_journal': data['retractions'][0]['journal']}, indent=2))"
echo ""
echo "------------------------------------------------------"
echo ""

echo "6. Get Specific Retraction"
echo "   GET /retractions/69157"
curl -s "http://localhost:8000/retractions/69157" | python -c "import sys, json; data=json.load(sys.stdin); print(json.dumps({'record_id': data['record_id'], 'title': data['title'], 'journal': data['journal'], 'retraction_nature': data['retraction_nature']}, indent=2))"
echo ""
echo "------------------------------------------------------"
echo ""

echo "7. List Top Authors"
echo "   GET /authors?limit=5"
curl -s "http://localhost:8000/authors?limit=5" | python -c "import sys, json; data=json.load(sys.stdin); print(f'Total authors: {data[\"total\"]}'); print('Top 5:'); [print(f'  {i+1}. {a[\"name\"]}: {a[\"retraction_count\"]} retractions') for i, a in enumerate(data['authors'])]"
echo ""
echo "------------------------------------------------------"
echo ""

echo "8. List Top Journals"
echo "   GET /journals?limit=5"
curl -s "http://localhost:8000/journals?limit=5" | python -c "import sys, json; data=json.load(sys.stdin); print(f'Total journals: {data[\"total\"]}'); print('Top 5:'); [print(f'  {i+1}. {j[\"name\"][:60]}...: {j[\"retraction_count\"]} retractions') for i, j in enumerate(data['journals'])]"
echo ""
echo "------------------------------------------------------"
echo ""

echo "9. Test 404 Error Handling"
echo "   GET /retractions/999999999"
curl -s "http://localhost:8000/retractions/999999999" | python -c "import sys, json; data=json.load(sys.stdin); print(json.dumps(data, indent=2))"
echo ""
echo "------------------------------------------------------"
echo ""

echo "✅ All API endpoints working correctly!"
echo ""
echo "Documentation available at:"
echo "  - Swagger UI: http://localhost:8000/docs"
echo "  - ReDoc: http://localhost:8000/redoc"
echo "  - OpenAPI JSON: http://localhost:8000/openapi.json"
echo ""
echo "======================================================"
